server:
  port: 9000 #???

############################################# Spring Cloud Ribbon ??????##########################
eureka:
  client:
    register-with-eureka: false #??????????????????????????
    fetch-registry: true  #????????????????????????
    service-url:
      defaultZone: http://192.168.43.111:7001/eureka #????????